trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'invicti-con'
    scanTypes: '0'
    scanWebSites: '4fdb7266-fdac-4dec-a190-aeac02e81366'
    scanWebSitesProfile: '14796d6d-4560-4bec-945a-aed701a0857a'