
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: netsparker-cloud@1
    inputs:
      apiConnection: 'invicti-1'
      scanTypes: '1'
      scanWebSites: 'b4a377dc-fc11-42d7-ecb8-aeb7020b8ec1'
      buildFail: true
      severity: 'DoNotFail'
      hasReport: true
      reportType: 'ExecutiveSummary'
      excludeAddressedIssues: false